spring:
  cloud:
    gateway:
      routes:
        - id: ratelimit
          uri: no://op
          predicates:
            - Path=/ratelimit
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
        - id: default
          uri: no://op
          predicates:
            - Path=/**